### ISSUE TITLE
Rename "Scouting Pairs" to  "Scouting Groups"  or "Scouting Teams"

### ISSUE THREAD

**Issue by AlexKempen** [FIRSTTeam102/ScoringApp-Serverless#131]
To help prevent confusion over the intended purpose and usage of the "Scouting Pairs" functionality in the app, it would be better if a more descriptive term like "Scouting Groups" or "Scouting Teams" was used instead. 

Of these two choices, I personally prefer "Scouting Teams", as this helps implies the co-operative nature of each group, but I don't feel strongly either way.

Additional discussion:
https://discord.com/channels/936402730317148170/936418650414530590/1077366905213562995

**Comment by JL102** [comment]
Good idea. I believe "groups" makes more sense, as we'd want to avoid confusion between scouting groups and FRC teams.
