### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by sloshyyy** [FIRSTTeam102/ScoringApp-Serverless#25]
I noticed that this codebase isn't licensed, but is a public repository.  I'm not a lawyer, but as far as I can tell this prevents the modification or reuse of this codebase, because unlicensed code is fully protected under copyright law.  This also potentially prevents 3rd parties from contributing, because of the complications that come with each contributor having copyright on their own contributions.  [choosealicense](https://choosealicense.com/) is a good resource to find an open source license, if you choose to do so.

[(More information on the restrictions around unlicensed code)](https://choosealicense.com/no-permission/)

**Comment by JL102** [comment]
Good point, thanks for bringing that up! I'll discuss that with the others. Out of curiosity, what led you to this repo? Are you part of an FRC team in NJ? (So far, we haven't gotten any traction on the github page; and only a small number of people visit the website so far.)

**Comment by sloshyyy** [comment]
I'm not from NJ but someone on my team had seen a post on chief about this.  Now that we're getting back into scouting work we were looking at what was already out there, and came back across the post.

**Comment by JL102** [comment]
Ah, great! Which team are you on? We're still working on bringing in new teams to Scoutradioz and we'd absolutely love if you're interested in joining and using it. It's free of course (in case my choice of words seemed to imply that we're trying to sell something); this is just volunteer work but I'm just really excited for our work to be used by more people. Also, if anyone on your team would be interested in helping us develop it, that would be fantastic! 

A. If your team is interested in using Scoutradioz next season, please fill out this form when you have a chance: https://docs.google.com/forms/d/1aFylB_3PbgIK2ridVfpgz8Z2r9QUZv6E-z57gjBUnPE/viewform?edit_requested=true
B. We have documentation on how to use the app here: https://github.com/FIRSTTeam102/ScoringApp-Serverless/wiki
C. We're working on a tutorial for students to follow to help get up-to-speed on the workflow we've been using for development, and the first page can be found here: https://github.com/FIRSTTeam102/ScoringApp-Serverless/wiki/Tutorial-#1:-Setup

**Comment by JL102** [comment]
AGPLv3 has been added to the main repository & the website now mentions the license on the bottom-left of the pull-out navigation menu.
