### ISSUE TITLE
Rework pit/match scouting assignment methods

### ISSUE THREAD

**Issue by Ardaglash** [FIRSTTeam102/ScoringApp-Serverless#66]
Specific design specs to be brainstormed, but the current "multi-step" process was a quick hack and has long past outlived its welcome

See also issue regarding updating pit scouting when team list is updated after assignments are made

**Comment by JL102** [comment]
Draft of the match scouting rework is done @ https://github.com/FIRSTTeam102/ScoringApp-Serverless/tree/new-scouting-assignments

As for pit scouting: Two folks now have requested that we support manually assigning pairs to specific teams. Maybe we can try and add that when we get to it in Voyager?
